### ISSUE TITLE
Doubt about file "mediapipe-0.8.9_cuda102-cp36-cp36m-linux_aarch64.whl

### ISSUE THREAD

**Issue by VieiraJardel** [anion0278/mediapipe-jetson#2]
What is the difference between the file "mediapipe-0.8.9_cuda102-cp36-cp36m-linux_aarch64.whl" in your repository and the file "mediapipe-dev-cp36-cp36m-linux_aarch64.whl" that comes in the mediapipe 0.8.9 folder that I downloaded directly from the mediapipe Git?

**Comment by anion0278** [comment]
hello, 
I'm not sure what exactly you mean by `mediapipe-dev-cp36-cp36m-linux_aarch64.whl` file, can you elaborate? `mediapipe-0.8.9_cuda102-cp36-cp36m-linux_aarch64.whl` file in this repo is especially for Jetson Nano, and I'm not aware of any distributions for Jetson Nano provided by Google itself.

**Comment by VieiraJardel** [comment]
I found it strange that the files were different, but now I understand that what's in your repository is specifically for installing on the Jetson Nano. Thank you for your attention and response!
