### ISSUE TITLE
OpenCV conflict 

### ISSUE THREAD

**Issue by VieiraJardel** [anion0278/mediapipe-jetson#5]
I compiled OpenCV 4.5.4 on my Jetson Nano, but during the 'python3 -m pip install --no-deps dist/mediapipe-0.8.9_cuda102-cp36-cp36m-linux_aarch64.whl' step, version 4.8.0 is being installed. I don't want to install this newer version because it results in a loss of GPU processing. Could you recommend something to address this issue of version conflict during installation?

**Comment by anion0278** [comment]
I have provided the commands for installation [here in readme](https://github.com/anion0278/mediapipe-jetson#installation-for-clean-jetpack-46---461---python-wheel), have you tried them?  

especially `pip3 install protobuf==3.19.4 opencv-python==4.5.3.56 dataclasses mediapipe-0.8.9_cuda102-cp36-linux_aarch64.whl`

**Comment by VieiraJardel** [comment]
I followed your commands and tried not to select OpenCV, but it didn't work. When I installed MediaPipe, OpenCV 4.8.1 was included automatically.

Is it possible to avoid installing OpenCV during the build and instead use dependencies from another installation, such as a custom-built version in my case?

**Comment by anion0278** [comment]
well, this command should have done exactly what you needed. Unfortunately, I don't have access to Jetson anymore to try to figure out other ways.
Nevertheless, I guess by 

> loss of GPU processing

you mean that your `OpenCV 4.5.4` is compiled with CUDA support. This is a common misconception that compiling OpenCV with CUDA makes all operations faster by running them on GPU. To actually use GPU you would still need to modify your code and actually upload data to-and-from GPU, see [tutorial](https://saturncloud.io/blog/how-to-use-opencv-with-cuda-support-in-python/). So unless your code is actually adapted to do that, you are not losing anything by installing a new non-cuda version of OpenCV.

**Comment by VieiraJardel** [comment]
Hi @anion0278 !
Can you please provide the link again? It's currently not working

**Comment by anion0278** [comment]
Hi, 
well, the link is now completely dead (removed), but you can find a similar tutorial [here](https://learnopencv.com/getting-started-opencv-cuda-module/).
